# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='Identifier')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('url', models.URLField(verbose_name='URL')),
                ('version', models.CharField(max_length=50, verbose_name='Version')),
                ('build', models.IntegerField(verbose_name='Build')),
                ('date', models.IntegerField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='Identifier')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('type', models.IntegerField(choices=[(0, 'Core'), (1, 'I/O'), (2, 'Splitter'), (3, 'Device'), (4, 'Configurator')], verbose_name='Type')),
                ('vendor', models.CharField(max_length=200, verbose_name='Vendor')),
                ('prefix', models.CharField(max_length=200, verbose_name='Prefix')),
                ('readme_markdown', models.TextField(verbose_name='Readme MarkDown')),
                ('readme_html', models.TextField(verbose_name='Readme HTML')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symcon.Library', verbose_name='Library')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='ModuleAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('deleted', models.BooleanField(default=False, verbose_name='Marked for deletion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symcon.Module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Module alias',
                'verbose_name_plural': 'Module aliases',
            },
        ),
        migrations.CreateModel(
            name='ModuleChildRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='Identifier')),
                ('deleted', models.BooleanField(default=False, verbose_name='Marked for deletion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symcon.Module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Module child requirement',
                'verbose_name_plural': 'Module child requirements',
            },
        ),
        migrations.CreateModel(
            name='ModuleImplementedRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='Identifier')),
                ('deleted', models.BooleanField(default=False, verbose_name='Marked for deletion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symcon.Module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Module implemented requirement',
                'verbose_name_plural': 'Module implemented requirements',
            },
        ),
        migrations.CreateModel(
            name='ModuleParentRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='Identifier')),
                ('deleted', models.BooleanField(default=False, verbose_name='Marked for deletion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symcon.Module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Module parent requirement',
                'verbose_name_plural': 'Module parent requirements',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='User')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_update', models.DateTimeField(verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AddField(
            model_name='library',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symcon.Repository', verbose_name='Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleparentrequirement',
            unique_together=set([('module', 'uuid')]),
        ),
        migrations.AlterUniqueTogether(
            name='moduleimplementedrequirement',
            unique_together=set([('module', 'uuid')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulechildrequirement',
            unique_together=set([('module', 'uuid')]),
        ),
        migrations.AlterUniqueTogether(
            name='modulealias',
            unique_together=set([('module', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('library', 'uuid')]),
        ),
        migrations.AlterUniqueTogether(
            name='library',
            unique_together=set([('repository', 'uuid')]),
        ),
    ]
