# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symcon', '0004_auto_20170101_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='library',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='library',
            name='repository',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='module',
            name='library',
        ),
        migrations.AlterUniqueTogether(
            name='modulealias',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modulealias',
            name='module',
        ),
        migrations.AlterUniqueTogether(
            name='modulechildrequirement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='modulechildrequirement',
            name='module',
        ),
        migrations.AlterUniqueTogether(
            name='moduleimplementedrequirement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduleimplementedrequirement',
            name='module',
        ),
        migrations.AlterUniqueTogether(
            name='moduleparentrequirement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduleparentrequirement',
            name='module',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='ModuleAlias',
        ),
        migrations.DeleteModel(
            name='ModuleChildRequirement',
        ),
        migrations.DeleteModel(
            name='ModuleImplementedRequirement',
        ),
        migrations.DeleteModel(
            name='ModuleParentRequirement',
        ),
    ]
