# -*- coding: UTF-8 -*-

DATE_FORMAT = "d. N Y"
TIME_FORMAT = "H:i"
DATETIME_FORMAT = DATE_FORMAT + " " + TIME_FORMAT + ":s"
YEAR_MONTH_FORMAT = "m.Y"
MONTH_DAY_FORMAT = "d.m."
SHORT_DATE_FORMAT = "d.m.Y"
SHORT_DATETIME_FORMAT = SHORT_DATE_FORMAT + " " + TIME_FORMAT
FIRST_DAY_OF_WEEK = 1
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = "."
NUMBER_GROUPING = 3
